# Generated by Django 6.0.4 on 2026-04-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_transaction_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('month', models.CharField(max_length=7)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('total_valuation', models.DecimalField(decimal_places=3, max_digits=15)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_stock', models.IntegerField()),
                ('valuation', models.DecimalField(decimal_places=3, max_digits=15)),
                ('stocks_json', models.JSONField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysnapshot')),
            ],
        ),
    ]
