# Generated by Django 6.0.4 on 2026-04-26 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorysnapshot_inventorysnapshotitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventorysnapshot',
            options={'ordering': ['-month'], 'verbose_name': 'inventory snapshot'},
        ),
        migrations.AlterModelOptions(
            name='inventorysnapshotitem',
            options={'verbose_name': 'snapshot item'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sku']},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterModelOptions(
            name='stocktakeitem',
            options={'verbose_name': 'stock take item'},
        ),
        migrations.AlterModelOptions(
            name='stocktakesession',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='month',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='ref',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorysnapshotitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_items', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_sessions', to='inventory.outlet'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='ref',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('BREAKAGE', 'Breakage'), ('WRITE_OFF', 'Write-off'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20),
        ),
    ]
